server:
  port: 9000

spring:
  application:
    name: save

  datasource:
    url: jdbc:mysql:// save-database-1.cnsy3pfkdksx.ap-northeast-2.rds.amazonaws.com
    username: save
    password: Team.Save22!
    driver-class-name: com.mysql.cj.jdbc.Driver