server:
  port: 9000

spring:
  application:
    name: save

  datasource:
    url: jdbc:mysql://
    username: save
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
#    TODO : ec2 이용해 서버배포할 때 aws-redis 엔드포인트로 변경해주기
    host: localhost
    port: 6379

  mail:
    host: smtp.naver.com
    port: 465
    username: save-children@naver.com
    password:
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true